import {
  TrendingUp, Zap, CloudRain, ShieldCheck, Home, Building, MapPin, Users,
  Settings2, Search, Type, FileText, Link2, Ban, LayoutTemplate,
  GitBranch, Target, Tag, Wrench, Layers, Filter, Globe, DollarSign,
  Gauge, Clock, Phone, BarChart3, RefreshCw, Bot, Building2, CheckCircle2,
  Siren, HardHat, CloudSnow, Thermometer, Wind, Flame, Snowflake, Fan,
  Droplet, Activity, AlertTriangle, Star,
  ArrowUpToLine, MousePointerClick, FormInput, Sparkles, TestTube2,
  Award, Briefcase, Scale, Gavel, Car, Truck, Bike, Shield, FileCheck,
  Stethoscope, HeartPulse, Footprints, Skull, Store, Warehouse,
  Trash2, Package, Sofa, Box, SprayCan, Bug, Rat, Leaf, Trees, Flower, Shovel, Sun, Moon, KeyRound, Lock,
  DoorClosed, DoorOpen, Hammer, PaintRoller, Brush, Scissors,
  Eye, EyeOff, ShieldAlert, CreditCard, Banknote, Receipt, PiggyBank,
  LineChart, TrendingDown, Coins, Wallet, Landmark, Stamp, FileSignature,
  BookOpen, GraduationCap, BriefcaseMedical, Cross, Plus, Minus, Equal,
  Divide, Percent, Wifi, Plug, Battery, BatteryCharging, Lightbulb,
  Construction, Ruler, PencilRuler, Compass, PenTool, DraftingCompass,
  Square, Circle, Triangle, Diamond, Hexagon, Octagon, Pentagon,
  Heart, ThumbsUp, Smile, Check, X, AlertCircle, Info, HelpCircle,
  Gift, Crown, Medal, Trophy, Flag, Bookmark, Calendar,
  CalendarDays, CalendarClock, Timer, Hourglass, Mail,
  MessageSquare, PhoneCall, PhoneForwarded, PhoneMissed, PhoneIncoming,
  PhoneOutgoing, Voicemail, Clipboard, ClipboardCheck, ClipboardList,
  Folder, FolderOpen, Save, Download, Upload, UploadCloud, FilePlus,
  FileSearch, FileCode, Table, Database, Server, HardDrive,
  Cloud, CloudOff, CloudDrizzle, CloudLightning, CloudFog, CloudHail,
  CloudMoon, CloudSun, Sunrise, Sunset, ThermometerSnowflake, ThermometerSun,
  Droplets, Waves, Tornado, Umbrella,
  Rainbow, Sparkle,
  AlignHorizontalDistributeCenter, AlignHorizontalJustifyCenter, Anchor,
  Armchair, ArrowLeftRight, Bath, BedDouble, Brain, BrickWall, Cable,
  CircleDot, Copy, Eraser, Flower2, Grid3x3, House, Key, Layers2, Move,
  PanelsTopLeft, PawPrint, PersonStanding, Pill, Refrigerator, Repeat,
  Replace, RotateCcw, ScanEye, Settings, ShieldX, ShoppingCart, Smartphone,
  Sprout, Swords, TreePine, User,
  FileSpreadsheet, GitCompare, Handshake, LayoutDashboard, ListChecks, Rocket, Unlock,
} from 'lucide-react';

import type { LucideIcon } from 'lucide-react';

const RAW_ICONS: Record<string, LucideIcon> = {
  TrendingUp, Zap, CloudRain, ShieldCheck, Home, Building, MapPin, Users,
  Settings2, Search, Type, FileText, Link2, Ban, LayoutTemplate,
  GitBranch, Target, Tag, Wrench, Layers, Filter, Globe, DollarSign,
  Gauge, Clock, Phone, BarChart3, RefreshCw, Bot, Building2, CheckCircle2,
  Siren, HardHat, CloudSnow, Thermometer, Wind, Flame, Snowflake, Fan,
  Droplet, Activity, AlertTriangle, Star,
  ArrowUpToLine, MousePointerClick, FormInput, Sparkles, TestTube2,
  Award, Briefcase, Scale, Gavel, Car, Truck, Bike, Shield, FileCheck,
  Stethoscope, HeartPulse, Footprints, Skull, Store, Warehouse,
  Trash2, Package, Sofa, Box, SprayCan, Bug, Rat, Leaf, Trees, Flower, Shovel, Sun, Moon, KeyRound, Lock,
  DoorClosed, DoorOpen, Hammer, PaintRoller, Brush, Scissors,
  Eye, EyeOff, ShieldAlert, CreditCard, Banknote, Receipt, PiggyBank,
  LineChart, TrendingDown, Coins, Wallet, Landmark, Stamp, FileSignature,
  BookOpen, GraduationCap, BriefcaseMedical, Cross, Plus, Minus, Equal,
  Divide, Percent, Wifi, Plug, Battery, BatteryCharging, Lightbulb,
  Construction, Ruler, PencilRuler, Compass, PenTool, DraftingCompass,
  Square, Circle, Triangle, Diamond, Hexagon, Octagon, Pentagon,
  Heart, ThumbsUp, Smile, Check, X, AlertCircle, Info, HelpCircle,
  Gift, Crown, Medal, Trophy, Flag, Bookmark, Calendar,
  CalendarDays, CalendarClock, Timer, Hourglass, Mail,
  MessageSquare, PhoneCall, PhoneForwarded, PhoneMissed, PhoneIncoming,
  PhoneOutgoing, Voicemail, Clipboard, ClipboardCheck, ClipboardList,
  Folder, FolderOpen, Save, Download, Upload, UploadCloud, FilePlus,
  FileSearch, FileCode, Table, Database, Server, HardDrive,
  Cloud, CloudOff, CloudDrizzle, CloudLightning, CloudFog, CloudHail,
  CloudMoon, CloudSun, Sunrise, Sunset, ThermometerSnowflake, ThermometerSun,
  Droplets, Waves, Tornado, Umbrella,
  Rainbow, Sparkle,
  AlignHorizontalDistributeCenter, AlignHorizontalJustifyCenter, Anchor,
  Armchair, ArrowLeftRight, Bath, BedDouble, Brain, BrickWall, Cable,
  CircleDot, Copy, Eraser, Flower2, Grid3x3, House, Key, Layers2, Move,
  PanelsTopLeft, PawPrint, PersonStanding, Pill, Refrigerator, Repeat,
  Replace, RotateCcw, ScanEye, Settings, ShieldX, ShoppingCart, Smartphone,
  Sprout, Swords, TreePine, User,
  FileSpreadsheet, GitCompare, Handshake, LayoutDashboard, ListChecks, Rocket, Unlock,
};

export function getIcon(name: string): LucideIcon {
  return RAW_ICONS[name] || Sparkles;
}
