import { Settings2, Target, Globe, MapPin, DollarSign, Gauge, Clock, Phone, Link2, BarChart3, Ban, Layers, RefreshCw, Search } from 'lucide-react';
import { AiInsight } from '@/components/marketing/roofing/ai-insight';

const SETTINGS = [
  {
    icon: Settings2,
    title: 'Campaign Name',
    description:
      'GrowthShift generates a structured campaign name — for example "Kelly Roofing | Roof Replacement | Florida" — so you can identify campaigns at a glance within your Google Ads account.',
  },
  {
    icon: Target,
    title: 'Campaign Goal',
    description:
      'The campaign goal is set to phone call leads for roofing companies because call conversions outperform form submissions in this vertical. GrowthShift configures conversion tracking for calls before the campaign goes live.',
  },
  {
    icon: Search,
    title: 'Search Campaign',
    description:
      'Every roofing campaign is built as a Google Ads search campaign — not Performance Max or Display — because homeowners actively searching for roofing services represent the highest intent audience.',
  },
  {
    icon: Globe,
    title: 'Google Search Network',
    description:
      'Your roofing search campaign targets the Google Search Network. Search partners are included by default but can be disabled if performance data shows low-quality traffic from partner sites.',
  },
  {
    icon: MapPin,
    title: 'Locations',
    description:
      'GrowthShift sets location targeting to the cities and counties you serve, extracted from your website. Manual location targeting prevents wasted spend in areas outside your operational radius.',
  },
  {
    icon: Globe,
    title: 'Languages',
    description:
      'Language targeting defaults to English. For roofing companies serving bilingual markets, GrowthShift can generate a second campaign with Spanish-language ad copy and keywords.',
  },
  {
    icon: DollarSign,
    title: 'Daily Budget',
    description:
      'The daily budget is set based on your service area size and average CPC for roofing keywords. GrowthShift recommends a starting budget and helps you scale once conversion data confirms profitability.',
  },
  {
    icon: Gauge,
    title: 'Bidding Strategy',
    description:
      'GrowthShift starts new roofing campaigns with Maximize Clicks to gather data quickly. Once you have 15+ conversions, it recommends switching to Maximize Conversions or Target CPA for efficient lead generation.',
  },
  {
    icon: BarChart3,
    title: 'Maximize Clicks & Maximize Conversions',
    description:
      'Maximize Clicks fills the funnel during the first weeks. Maximize Conversions takes over once enough conversion data exists. Target CPA further refines bidding by setting a maximum cost per roofing phone call lead.',
  },
  {
    icon: Clock,
    title: 'Ad Schedule',
    description:
      'Roofing ads run Monday through Sunday, 6 AM to 10 PM by default. GrowthShift adjusts the schedule based on when you can answer the phone — missed calls are wasted budget in roofing lead generation.',
  },
  {
    icon: Phone,
    title: 'Call Reporting & Call Extensions',
    description:
      'Call reporting tracks every call generated by your roofing ads. Call extensions display your phone number directly in the ad, letting homeowners call without visiting your landing page first.',
  },
  {
    icon: Link2,
    title: 'Location Extensions',
    description:
      'Location extensions show your roofing company address alongside your ad, critical for local trust and for appearing in Google Maps results when homeowners search "roofers near me".',
  },
  {
    icon: BarChart3,
    title: 'Conversion Tracking',
    description:
      'Conversion tracking is configured for phone calls and form submissions. Without it you cannot measure roofing cost per lead or optimize toward target CPA. GrowthShift sets this up as part of campaign setup.',
  },
  {
    icon: Layers,
    title: 'Phrase Match Strategy',
    description:
      'All roofing keyword groups use phrase match by default, giving you reach without the waste of broad match. This is the single most important setting for controlling roofing PPC costs.',
  },
  {
    icon: Ban,
    title: 'Negative Keywords',
    description:
      'A roofing negative keywords list is applied at campaign setup and expanded weekly from search term reports. This protects your budget from job seekers, DIY homeowners, and wholesale supply searches.',
  },
  {
    icon: Gauge,
    title: 'Quality Score',
    description:
      'High Quality Score lowers your cost per click and improves ad position. GrowthShift maximizes it by aligning roofing keywords, ad copy, and landing page content within each ad group.',
  },
  {
    icon: RefreshCw,
    title: 'Campaign Optimization & Management',
    description:
      'GrowthShift provides ongoing campaign optimization and campaign management through AI recommendations — search term review, bid adjustments, and ad copy testing — without the overhead of a roofing PPC agency.',
  },
];

export function RoofingCampaignSettingsSection() {
  return (
    <section className="border-b border-border/60 py-16 lg:py-20 bg-muted/20">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mb-10 max-w-2xl">
          <span className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">
            Campaign Settings
          </span>
          <h2 className="mt-3 text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            Google Ads Campaign Settings
          </h2>
          <p className="mt-3 text-base text-muted-foreground">
            Every roofing search campaign needs dozens of settings configured correctly. GrowthShift builds
            all of them automatically from your website analysis — from bidding strategy to ad schedule to
            conversion tracking.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {SETTINGS.map((setting) => {
            const Icon = setting.icon;
            return (
              <div key={setting.title} className="rounded-2xl border border-border bg-card p-6 shadow-sm">
                <div className="mb-4 flex h-10 w-10 items-center justify-center rounded-xl border border-border bg-muted">
                  <Icon className="h-5 w-5 text-foreground" />
                </div>
                <h3 className="text-base font-semibold text-foreground">{setting.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{setting.description}</p>
              </div>
            );
          })}
        </div>

        <div className="mt-6 max-w-2xl">
          <AiInsight>
            Starting with Maximize Clicks for the first 2–3 weeks gathers conversion data fast. Switch to Maximize Conversions once you have 15+ conversions.
          </AiInsight>
        </div>
      </div>
    </section>
  );
}
